version: "3.8"
#
# Services definitions
#
services:
  frontend:
    image: kooldev/node:16
    command: ["npm", "run", "dev", "--", "-p", "${FRONTEND_PORT:-3000}"]
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      ASUSER: "${ASUSER:-0}"
      UID: "${UID:-0}"
      FRONTEND_PORT: "${FRONTEND_PORT:-3000}"
    volumes:
      - .:/app:delegated
    working_dir: /app/frontend
    networks:
      - neolab_local
  backend:
    image: kooldev/node:16
    command: ["npm", "run", "start:dev"]
    ports:
      - "${BACKEND_PORT:-8001}:${BACKEND_PORT:-8001}"
    environment:
      ASUSER: "${ASUSER:-0}"
      UID: "${UID:-0}"
      BACKEND_PORT: "${BACKEND_PORT:-8001}"
    volumes:
      - ./backend:/app:delegated
    networks:
      - neolab_local
  database:
    image: postgres:13-alpine
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - database:/var/lib/postgresql/data:delegated
    networks:
      - neolab_local
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "DATABASE_NAME", "-U", "DATABASE_USERNAME"]
  cache:
    image: redis:6-alpine
    volumes:
      - cache:/data:delegated
    networks:
      - neolab_local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_HTTP_ADDR=${MEILI_HTTP_ADDR}
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/data.ms
    networks:
      - neolab_local
  minio:
    image: minio/minio:latest
    hostname: minio
    restart: always
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      MINIO_SERVER_URL: "${AWS_HOST}"
      MINIO_REGION: ${AWS_REGION}
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - neolab_local
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9002:9000"
      - "9001:9001"
    depends_on:
      - minio
    networks:
      neolab_local:

#
# Networks definitions
#
networks:
  neolab_local:
  neolab_common:
volumes:
  database:
  cache:
  meilisearch-data:
  minio-data:


